services:
  mongodb:
    image: mongo:5.0.6
    container_name: mongodb-cnt
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGO_INITDB_DATABASE=livraria_alura
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=superroot
      # Nome do banco de dados = livraria_alura
      # Nome da coleção = livros
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express-cnt
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=superroot
      - ME_CONFIG_MONGODB_SERVER=mongodb-cnt
    depends_on:
      - mongodb