services:
  mongodb:
    image: mongo:5.0.6
    container_name: mongodb-cnt
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=livraria_user
      - MONGO_INITDB_ROOT_PASSWORD=superSecret03
      #- MONGO_INITDB_DATABASE=livraria_api
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express-cnt
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=livraria_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=superSecret03
      - ME_CONFIG_MONGODB_SERVER=mongodb-cnt